#!/usr/bin/env python3
"""Rasterise a 6x10 ASCII bitmap font for the display (needs pillow). Output: font6x10.h"""
import os, sys
from PIL import Image, ImageDraw, ImageFont
W, H = 6, 10
cands = ["/System/Library/Fonts/Menlo.ttc", "/System/Library/Fonts/Monaco.ttf", "/System/Library/Fonts/SFNSMono.ttf",
         "/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf"]
path = next(p for p in cands if os.path.exists(p))
font = ImageFont.truetype(path, 10)
rows = []
for c in range(32, 127):
    img = Image.new("1", (W, H), 0)
    ImageDraw.Draw(img).text((0, -1), chr(c), font=font, fill=1)
    col = []
    for y in range(H):
        b = 0
        for x in range(W):
            if img.getpixel((x, y)): b |= 0x80 >> x
        col.append(b)
    rows.append(col)
out = sys.argv[1] if len(sys.argv) > 1 else "font6x10.h"
with open(out, "w") as f:
    f.write(f"// Generated by tools/gen_font.py from {os.path.basename(path)}: ASCII 32..126, {W}x{H}, row-major, MSB = left.\n")
    f.write("#pragma once\n#include <stdint.h>\n#define FONT_W 6\n#define FONT_H 10\n")
    f.write("static const uint8_t font6x10[95][10] = {\n")
    for c, col in zip(range(32, 127), rows):
        name = "backslash" if chr(c) == "\\" else chr(c)
        f.write("    {" + ", ".join("0x%02X" % b for b in col) + "},  // " + name + "\n")
    f.write("};\n")
print("font from", path)
